services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tennis
    depends_on:
      - postgres
    command: sh -c "
      until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT; do
        echo 'Waiting for PostgreSQL...';
        sleep 2;
      done;
      psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -f /app/src/migrations/V1__init.sql &&
      psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -f /app/src/migrations/V2__seed_data.sql &&
      npm run start:dev"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tennis
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
